services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $apiHost: "%stfalcon_api.api_host%"
            $jsonSchemaDir: "%stfalcon_api.json_schema_dir%"
            $environment: '%env(APP_ENV)%'
            iterable $errorResponseProcessors: !tagged_iterator 'stfalcon_api.exception_response_processor'

    StfalconStudio\ApiBundle\:
        resource: '../../{EventListener,Request,Security,Serializer,Service,Util,Validator}/'

    StfalconStudio\ApiBundle\EventListener\ORM\Aggregate\AggregatePartListener:
        class: StfalconStudio\ApiBundle\EventListener\ORM\Aggregate\AggregatePartListener
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    Predis\Client:
        class: Predis\Client

    JsonSchema\Validator:
        class: JsonSchema\Validator
